### ISSUE TITLE
[13.0] attribute_set_completeness: missing values on tree view

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/odoo-pim#59]
Since the migration, 2 columns disappeared from the tree view.
I was expecting to get completion_state and completion_rate here:

![image](https://user-images.githubusercontent.com/7813258/95578559-596fac00-0a34-11eb-8129-9b37946b88db.png)

**Comment by simahawk** [comment]
@Cedric-Pigeon I don't see those fields in the tree view of the product in any version https://github.com/shopinvader/odoo-pim/blob/10.0/product_attribute_set_completeness/views/product_template_view.xml 
Am I missing anything?

**Comment by simahawk** [comment]
ah now I see: the ctx is `pim` module. Was not clear, sorry :sweat_smile: 
I'll check, but I haven't touched that module as it was already migrated.

**Comment by simahawk** [comment]
I see them here https://github.com/shopinvader/odoo-pim/commit/b68116a1c299692a6625a44a92aaf7c7961b0796#diff-11cba8b9ad79d8d5e2ae00da3ccd4335
but not here https://github.com/shopinvader/odoo-pim/blob/13.0/pim/views/product_view.xml because the migration happened few days before.

I'll cherry pick changes for PIM then.

**Comment by simahawk** [comment]
#55 contains the fix
